#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.14
# from Racc grammer file "".
#

###### racc/parser.rb begin
unless $".index 'racc/parser.rb'
$".push 'racc/parser.rb'
self.class.module_eval(<<'...end racc/parser.rb/module_eval...', 'racc/parser.rb', 1)
#
# $Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $
#
# Copyright (c) 1999-2006 Minero Aoki
#
# This program is free software.
# You can distribute/modify this program under the same terms of ruby.
#
# As a special exception, when this code is copied by Racc
# into a Racc output file, you may use that output file
# without restriction.
#

require 'racc/info'

unless defined?(NotImplementedError)
  NotImplementedError = NotImplementError # :nodoc:
end

module Racc
  class ParseError < StandardError; end
end
unless defined?(::ParseError)
  ParseError = Racc::ParseError
end

# Racc is a LALR(1) parser generator.
# It is written in Ruby itself, and generates Ruby programs.
#
# == Command-line Reference
#
#     racc [-o<var>filename</var>] [--output-file=<var>filename</var>]
#          [-e<var>rubypath</var>] [--embedded=<var>rubypath</var>]
#          [-v] [--verbose]
#          [-O<var>filename</var>] [--log-file=<var>filename</var>]
#          [-g] [--debug]
#          [-E] [--embedded]
#          [-l] [--no-line-convert]
#          [-c] [--line-convert-all]
#          [-a] [--no-omit-actions]
#          [-C] [--check-only]
#          [-S] [--output-status]
#          [--version] [--copyright] [--help] <var>grammarfile</var>
#
# [+filename+]
#   Racc grammar file. Any extention is permitted.
# [-o+outfile+, --output-file=+outfile+]
#   A filename for output. default is <+filename+>.tab.rb
# [-O+filename+, --log-file=+filename+]
#   Place logging output in file +filename+.
#   Default log file name is <+filename+>.output.
# [-e+rubypath+, --executable=+rubypath+]
#   output executable file(mode 755). where +path+ is the Ruby interpreter.
# [-v, --verbose]
#   verbose mode. create +filename+.output file, like yacc's y.output file.
# [-g, --debug]
#   add debug code to parser class. To display debuggin information,
#   use this '-g' option and set @yydebug true in parser class.
# [-E, --embedded]
#   Output parser which doesn't need runtime files (racc/parser.rb).
# [-C, --check-only]
#   Check syntax of racc grammer file and quit.
# [-S, --output-status]
#   Print messages time to time while compiling.
# [-l, --no-line-convert]
#   turns off line number converting.
# [-c, --line-convert-all]
#   Convert line number of actions, inner, header and footer.
# [-a, --no-omit-actions]
#   Call all actions, even if an action is empty.
# [--version]
#   print Racc version and quit.
# [--copyright]
#   Print copyright and quit.
# [--help]
#   Print usage and quit.
#
# == Generating Parser Using Racc
#
# To compile Racc grammar file, simply type:
#
#   $ racc parse.y
#
# This creates Ruby script file "parse.tab.y". The -o option can change the output filename.
#
# == Writing A Racc Grammar File
#
# If you want your own parser, you have to write a grammar file.
# A grammar file contains the name of your parser class, grammar for the parser,
# user code, and anything else.
# When writing a grammar file, yacc's knowledge is helpful.
# If you have not used yacc before, Racc is not too difficult.
#
# Here's an example Racc grammar file.
#
#   class Calcparser
#   rule
#     target: exp { print val[0] }
#
#     exp: exp '+' exp
#        | exp '*' exp
#        | '(' exp ')'
#        | NUMBER
#   end
#
# Racc grammar files resemble yacc files.
# But (of course), this is Ruby code.
# yacc's $$ is the 'result', $0, $1... is
# an array called 'val', and $-1, $-2... is an array called '_values'.
#
# See the {Grammar File Reference}[rdoc-ref:lib/racc/rdoc/grammar.en.rdoc] for
# more information on grammar files.
#
# == Parser
#
# Then you must prepare the parse entry method. There are two types of
# parse methods in Racc, Racc::Parser#do_parse and Racc::Parser#yyparse
#
# Racc::Parser#do_parse is simple.
#
# It's yyparse() of yacc, and Racc::Parser#next_token is yylex().
# This method must returns an array like [TOKENSYMBOL, ITS_VALUE].
# EOF is [false, false].
# (TOKENSYMBOL is a Ruby symbol (taken from String#intern) by default.
# If you want to change this, see the grammar reference.
#
# Racc::Parser#yyparse is little complicated, but useful.
# It does not use Racc::Parser#next_token, instead it gets tokens from any iterator.
#
# For example, <code>yyparse(obj, :scan)</code> causes
# calling +obj#scan+, and you can return tokens by yielding them from +obj#scan+.
#
# == Debugging
#
# When debugging, "-v" or/and the "-g" option is helpful.
#
# "-v" creates verbose log file (.output).
# "-g" creates a "Verbose Parser".
# Verbose Parser prints the internal status when parsing.
# But it's _not_ automatic.
# You must use -g option and set +@yydebug+ to +true+ in order to get output.
# -g option only creates the verbose parser.
#
# === Racc reported syntax error.
#
# Isn't there too many "end"?
# grammar of racc file is changed in v0.10.
#
# Racc does not use '%' mark, while yacc uses huge number of '%' marks..
#
# === Racc reported "XXXX conflicts".
#
# Try "racc -v xxxx.y".
# It causes producing racc's internal log file, xxxx.output.
#
# === Generated parsers does not work correctly
#
# Try "racc -g xxxx.y".
# This command let racc generate "debugging parser".
# Then set @yydebug=true in your parser.
# It produces a working log of your parser.
#
# == Re-distributing Racc runtime
#
# A parser, which is created by Racc, requires the Racc runtime module;
# racc/parser.rb.
#
# Ruby 1.8.x comes with Racc runtime module,
# you need NOT distribute Racc runtime files.
#
# If you want to include the Racc runtime module with your parser.
# This can be done by using '-E' option:
#
#   $ racc -E -omyparser.rb myparser.y
#
# This command creates myparser.rb which `includes' Racc runtime.
# Only you must do is to distribute your parser file (myparser.rb).
#
# Note: parser.rb is LGPL, but your parser is not.
# Your own parser is completely yours.
module Racc

  unless defined?(Racc_No_Extentions)
    Racc_No_Extentions = false # :nodoc:
  end

  class Parser

    Racc_Runtime_Version = ::Racc::VERSION
    Racc_Runtime_Revision = '$Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $'

    Racc_Runtime_Core_Version_R = ::Racc::VERSION
    Racc_Runtime_Core_Revision_R = '$Id: 2bd697d1146b280d8d3878e21e556ef769484a37 $'.split[1]
    begin
      if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
        require 'racc/cparse-jruby.jar'
        com.headius.racc.Cparse.new.load(JRuby.runtime, false)
      else
        require 'racc/cparse'
      end
    # Racc_Runtime_Core_Version_C  = (defined in extention)
      Racc_Runtime_Core_Revision_C = Racc_Runtime_Core_Id_C.split[2]
      unless new.respond_to?(:_racc_do_parse_c, true)
        raise LoadError, 'old cparse.so'
      end
      if Racc_No_Extentions
        raise LoadError, 'selecting ruby version of racc runtime core'
      end

      Racc_Main_Parsing_Routine    = :_racc_do_parse_c # :nodoc:
      Racc_YY_Parse_Method         = :_racc_yyparse_c # :nodoc:
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_C # :nodoc:
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_C # :nodoc:
      Racc_Runtime_Type            = 'c' # :nodoc:
    rescue LoadError
puts $!
puts $!.backtrace
      Racc_Main_Parsing_Routine    = :_racc_do_parse_rb
      Racc_YY_Parse_Method         = :_racc_yyparse_rb
      Racc_Runtime_Core_Version    = Racc_Runtime_Core_Version_R
      Racc_Runtime_Core_Revision   = Racc_Runtime_Core_Revision_R
      Racc_Runtime_Type            = 'ruby'
    end

    def Parser.racc_runtime_type # :nodoc:
      Racc_Runtime_Type
    end

    def _racc_setup
      @yydebug = false unless self.class::Racc_debug_parser
      @yydebug = false unless defined?(@yydebug)
      if @yydebug
        @racc_debug_out = $stderr unless defined?(@racc_debug_out)
        @racc_debug_out ||= $stderr
      end
      arg = self.class::Racc_arg
      arg[13] = true if arg.size < 14
      arg
    end

    def _racc_init_sysvars
      @racc_state  = [0]
      @racc_tstack = []
      @racc_vstack = []

      @racc_t = nil
      @racc_val = nil

      @racc_read_next = true

      @racc_user_yyerror = false
      @racc_error_status = 0
    end

    # The entry point of the parser. This method is used with #next_token.
    # If Racc wants to get token (and its value), calls next_token.
    #
    # Example:
    #     def parse
    #       @q = [[1,1],
    #             [2,2],
    #             [3,3],
    #             [false, '$']]
    #       do_parse
    #     end
    #
    #     def next_token
    #       @q.shift
    #     end
    def do_parse
      __send__(Racc_Main_Parsing_Routine, _racc_setup(), false)
    end

    # The method to fetch next token.
    # If you use #do_parse method, you must implement #next_token.
    #
    # The format of return value is [TOKEN_SYMBOL, VALUE].
    # +token-symbol+ is represented by Ruby's symbol by default, e.g. :IDENT
    # for 'IDENT'.  ";" (String) for ';'.
    #
    # The final symbol (End of file) must be false.
    def next_token
      raise NotImplementedError, "#{self.class}\#next_token is not defined"
    end

    def _racc_do_parse_rb(arg, in_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars
      tok = act = i = nil

      catch(:racc_end_parse) {
        while true
          if i = action_pointer[@racc_state[-1]]
            if @racc_read_next
              if @racc_t != 0   # not EOF
                tok, @racc_val = next_token()
                unless tok      # EOF
                  @racc_t = 0
                else
                  @racc_t = (token_table[tok] or 1)   # error token
                end
                racc_read_token(@racc_t, tok, @racc_val) if @yydebug
                @racc_read_next = false
              end
            end
            i += @racc_t
            unless i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
          else
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end
        end
      }
    end

    # Another entry point for the parser.
    # If you use this method, you must implement RECEIVER#METHOD_ID method.
    #
    # RECEIVER#METHOD_ID is a method to get next token.
    # It must 'yield' the token, which format is [TOKEN-SYMBOL, VALUE].
    def yyparse(recv, mid)
      __send__(Racc_YY_Parse_Method, recv, mid, _racc_setup(), false)
    end

    def _racc_yyparse_rb(recv, mid, arg, c_debug)
      action_table, action_check, action_default, action_pointer,
      _,            _,            _,              _,
      _,            _,            token_table,    * = arg

      _racc_init_sysvars

      catch(:racc_end_parse) {
        until i = action_pointer[@racc_state[-1]]
          while act = _racc_evalact(action_default[@racc_state[-1]], arg)
            ;
          end
        end
        recv.__send__(mid) do |tok, val|
          unless tok
            @racc_t = 0
          else
            @racc_t = (token_table[tok] or 1)   # error token
          end
          @racc_val = val
          @racc_read_next = false

          i += @racc_t
          unless i >= 0 and
                 act = action_table[i] and
                 action_check[i] == @racc_state[-1]
            act = action_default[@racc_state[-1]]
          end
          while act = _racc_evalact(act, arg)
            ;
          end

          while !(i = action_pointer[@racc_state[-1]]) ||
                ! @racc_read_next ||
                @racc_t == 0  # $
            unless i and i += @racc_t and
                   i >= 0 and
                   act = action_table[i] and
                   action_check[i] == @racc_state[-1]
              act = action_default[@racc_state[-1]]
            end
            while act = _racc_evalact(act, arg)
              ;
            end
          end
        end
      }
    end

    ###
    ### common
    ###

    def _racc_evalact(act, arg)
      action_table, action_check, _, action_pointer,
      _,            _,            _, _,
      _,            _,            _, shift_n,
      reduce_n,     * = arg
      nerr = 0   # tmp

      if act > 0 and act < shift_n
        #
        # shift
        #
        if @racc_error_status > 0
          @racc_error_status -= 1 unless @racc_t <= 1 # error token or EOF
        end
        @racc_vstack.push @racc_val
        @racc_state.push act
        @racc_read_next = true
        if @yydebug
          @racc_tstack.push @racc_t
          racc_shift @racc_t, @racc_tstack, @racc_vstack
        end

      elsif act < 0 and act > -reduce_n
        #
        # reduce
        #
        code = catch(:racc_jump) {
          @racc_state.push _racc_do_reduce(arg, act)
          false
        }
        if code
          case code
          when 1 # yyerror
            @racc_user_yyerror = true   # user_yyerror
            return -reduce_n
          when 2 # yyaccept
            return shift_n
          else
            raise '[Racc Bug] unknown jump code'
          end
        end

      elsif act == shift_n
        #
        # accept
        #
        racc_accept if @yydebug
        throw :racc_end_parse, @racc_vstack[0]

      elsif act == -reduce_n
        #
        # error
        #
        case @racc_error_status
        when 0
          unless arg[21]    # user_yyerror
            nerr += 1
            on_error @racc_t, @racc_val, @racc_vstack
          end
        when 3
          if @racc_t == 0   # is $
            # We're at EOF, and another error occurred immediately after
            # attempting auto-recovery
            throw :racc_end_parse, nil
          end
          @racc_read_next = true
        end
        @racc_user_yyerror = false
        @racc_error_status = 3
        while true
          if i = action_pointer[@racc_state[-1]]
            i += 1   # error token
            if  i >= 0 and
                (act = action_table[i]) and
                action_check[i] == @racc_state[-1]
              break
            end
          end
          throw :racc_end_parse, nil if @racc_state.size <= 1
          @racc_state.pop
          @racc_vstack.pop
          if @yydebug
            @racc_tstack.pop
            racc_e_pop @racc_state, @racc_tstack, @racc_vstack
          end
        end
        return act

      else
        raise "[Racc Bug] unknown action #{act.inspect}"
      end

      racc_next_state(@racc_state[-1], @racc_state) if @yydebug

      nil
    end

    def _racc_do_reduce(arg, act)
      _,          _,            _,            _,
      goto_table, goto_check,   goto_default, goto_pointer,
      nt_base,    reduce_table, _,            _,
      _,          use_result,   * = arg

      state = @racc_state
      vstack = @racc_vstack
      tstack = @racc_tstack

      i = act * -3
      len       = reduce_table[i]
      reduce_to = reduce_table[i+1]
      method_id = reduce_table[i+2]
      void_array = []

      tmp_t = tstack[-len, len] if @yydebug
      tmp_v = vstack[-len, len]
      tstack[-len, len] = void_array if @yydebug
      vstack[-len, len] = void_array
      state[-len, len]  = void_array

      # tstack must be updated AFTER method call
      if use_result
        vstack.push __send__(method_id, tmp_v, vstack, tmp_v[0])
      else
        vstack.push __send__(method_id, tmp_v, vstack)
      end
      tstack.push reduce_to

      racc_reduce(tmp_t, reduce_to, tstack, vstack) if @yydebug

      k1 = reduce_to - nt_base
      if i = goto_pointer[k1]
        i += state[-1]
        if i >= 0 and (curstate = goto_table[i]) and goto_check[i] == k1
          return curstate
        end
      end
      goto_default[k1]
    end

    # This method is called when a parse error is found.
    #
    # ERROR_TOKEN_ID is an internal ID of token which caused error.
    # You can get string representation of this ID by calling
    # #token_to_str.
    #
    # ERROR_VALUE is a value of error token.
    #
    # value_stack is a stack of symbol values.
    # DO NOT MODIFY this object.
    #
    # This method raises ParseError by default.
    #
    # If this method returns, parsers enter "error recovering mode".
    def on_error(t, val, vstack)
      raise ParseError, sprintf("\nparse error on value %s (%s)",
                                val.inspect, token_to_str(t) || '?')
    end

    # Enter error recovering mode.
    # This method does not call #on_error.
    def yyerror
      throw :racc_jump, 1
    end

    # Exit parser.
    # Return value is Symbol_Value_Stack[0].
    def yyaccept
      throw :racc_jump, 2
    end

    # Leave error recovering mode.
    def yyerrok
      @racc_error_status = 0
    end

    # For debugging output
    def racc_read_token(t, tok, val)
      @racc_debug_out.print 'read    '
      @racc_debug_out.print tok.inspect, '(', racc_token2str(t), ') '
      @racc_debug_out.puts val.inspect
      @racc_debug_out.puts
    end

    def racc_shift(tok, tstack, vstack)
      @racc_debug_out.puts "shift   #{racc_token2str tok}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_reduce(toks, sim, tstack, vstack)
      out = @racc_debug_out
      out.print 'reduce '
      if toks.empty?
        out.print ' <none>'
      else
        toks.each {|t| out.print ' ', racc_token2str(t) }
      end
      out.puts " --> #{racc_token2str(sim)}"
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_accept
      @racc_debug_out.puts 'accept'
      @racc_debug_out.puts
    end

    def racc_e_pop(state, tstack, vstack)
      @racc_debug_out.puts 'error recovering mode: pop token'
      racc_print_states state
      racc_print_stacks tstack, vstack
      @racc_debug_out.puts
    end

    def racc_next_state(curstate, state)
      @racc_debug_out.puts  "goto    #{curstate}"
      racc_print_states state
      @racc_debug_out.puts
    end

    def racc_print_stacks(t, v)
      out = @racc_debug_out
      out.print '        ['
      t.each_index do |i|
        out.print ' (', racc_token2str(t[i]), ' ', v[i].inspect, ')'
      end
      out.puts ' ]'
    end

    def racc_print_states(s)
      out = @racc_debug_out
      out.print '        ['
      s.each {|st| out.print ' ', st }
      out.puts ' ]'
    end

    def racc_token2str(tok)
      self.class::Racc_token_to_s_table[tok] or
          raise "[Racc Bug] can't convert token #{tok} to string"
    end

    # Convert internal ID of token symbol to the string.
    def token_to_str(t)
      self.class::Racc_token_to_s_table[t]
    end

  end

end

...end racc/parser.rb/module_eval...
end
###### racc/parser.rb end


require_relative 'Lexer'
require_relative 'AST_yo'


class ErrorSintactico < RuntimeError
  def initialize(token)
    @token = token
  end

  def to_s
    "Error de sintaxis en linea #{@token.linea}, columna #{@token.columna}, token '#{@token.contenido}' inesperado."
  end
end

class Parser < Racc::Parser

module_eval(<<'...end Parser.y/module_eval...', 'Parser.y', 199)

    def initialize(lexer)
      @lexer = lexer
      @yydebug = true
      super()
    end 

    def on_error(id, token, stack)
      raise ErrorSintactico.new(token)
    end

    def next_token
      @lexer.shift
    end

    def parse
      do_parse
    end
...end Parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    28,     4,    29,    84,    74,     5,    73,    27,    10,     8,
    13,    72,    83,    25,     6,   108,     7,     9,    12,   109,
   110,   111,    23,     3,    26,     4,    21,    22,    76,     5,
   106,   136,    10,     8,    79,    28,    24,    29,     6,   108,
     7,     9,    27,   109,   110,   111,    20,    16,    25,    64,
    13,    52,    55,    50,   118,   136,   119,    23,    12,    26,
     4,    21,    22,    15,     5,   145,   121,    10,     8,    45,
    28,    24,    29,     6,   108,     7,     9,    27,   109,   110,
   111,    20,    16,    25,    53,    54,    52,    55,    50,    62,
    65,    66,    23,   123,    26,     4,    21,    22,    45,     5,
    65,    66,    10,     8,    42,    28,    24,    29,     6,    45,
     7,     9,    27,    52,    55,    50,    20,    16,    25,   128,
    39,    28,   130,    29,    37,   132,   133,    23,    27,    26,
    30,    21,    22,    15,    25,    53,    54,    52,    55,    50,
   138,    24,   139,    23,   140,    26,     4,    21,    22,   141,
     5,    20,    35,    10,     8,   142,    28,    24,    29,     6,
    82,     7,     9,    27,   144,    11,   146,    20,    16,    25,
    53,    54,    52,    55,    50,   147,   148,    41,    23,   nil,
    26,     4,    21,    22,   nil,     5,   134,   nil,    10,     8,
   nil,    28,    24,    29,     6,   nil,     7,     9,    27,    28,
   nil,    29,    20,    16,    25,   nil,    27,   nil,   nil,   nil,
   nil,   nil,    25,    23,   nil,    26,   nil,    21,    22,   nil,
   nil,    23,   nil,    26,   nil,    21,    22,    33,   nil,    28,
   nil,    29,   nil,   nil,   nil,    24,    27,    20,    35,   nil,
   nil,   nil,    25,   nil,   nil,    20,    35,   nil,   nil,   nil,
   nil,    23,   nil,    26,     4,    21,    22,   nil,     5,   nil,
   nil,    10,     8,   nil,    28,    24,    29,     6,   nil,     7,
     9,    27,   nil,   nil,   nil,    20,    16,    25,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    23,   nil,    26,   nil,
    21,    22,    28,   nil,    29,   nil,   nil,   nil,   nil,    27,
    24,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,
    20,    35,   nil,   nil,    23,   nil,    26,     4,    21,    22,
   nil,     5,   129,   nil,    10,     8,   nil,    28,    24,    29,
     6,   nil,     7,     9,    27,    28,   nil,    29,    20,    16,
    25,   nil,    27,   nil,   nil,   nil,   nil,   nil,    25,    23,
   nil,    26,   nil,    21,    22,   nil,   nil,    23,   nil,    26,
   nil,    21,    22,    24,   nil,    28,   nil,    29,   nil,   nil,
   nil,    24,    27,    20,    35,   nil,   nil,   nil,    25,   nil,
   nil,    20,    35,   nil,   nil,   nil,   nil,    23,   nil,    26,
     4,    21,    22,   nil,     5,   nil,   nil,    10,     8,   nil,
    28,    24,    29,     6,   nil,     7,     9,    27,    28,   nil,
    29,    20,    16,    25,   nil,    27,   nil,   nil,   nil,   nil,
   nil,    25,    23,   nil,    26,   nil,    21,    22,   nil,   nil,
    23,   nil,    26,   nil,    21,    22,    24,   nil,    28,   nil,
    29,   nil,   nil,   nil,    24,    27,    20,    35,   nil,   nil,
   nil,    25,   nil,   nil,    20,    35,   nil,   nil,   nil,   nil,
    23,   nil,    26,     4,    21,    22,   nil,     5,    46,   nil,
    10,     8,   nil,    28,    24,    29,     6,   nil,     7,     9,
    27,   nil,   nil,   nil,    20,    16,    25,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    23,   nil,    26,   nil,    21,
    22,    28,   nil,    29,   nil,   nil,   nil,   nil,    27,    24,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    20,
    35,   nil,   nil,    23,   nil,    26,     4,    21,    22,   nil,
     5,   117,   nil,    10,     8,   nil,    28,    24,    29,     6,
   nil,     7,     9,    27,    28,   nil,    29,    20,    16,    25,
   nil,    27,    28,   nil,    29,   nil,   nil,    25,    23,    27,
    26,   nil,    21,    22,   nil,    25,    23,   nil,    26,   nil,
    21,    22,    24,   nil,    23,   nil,    26,   nil,    21,    22,
    24,   nil,    20,    35,   nil,   nil,   nil,    28,    24,    29,
    20,    35,   nil,   nil,    27,    28,   nil,    29,    20,    35,
    25,   nil,    27,    28,   nil,    29,   nil,   nil,    25,    23,
    27,    26,   nil,    21,    22,   nil,    25,    23,   nil,    26,
   nil,    21,    22,    24,   nil,    23,   nil,    26,   nil,    21,
    22,    24,   nil,    20,    35,   nil,   nil,   nil,    28,    24,
    29,    20,    35,   nil,   nil,    27,   nil,   nil,   nil,    20,
    35,    25,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    23,   nil,    26,     4,    21,    22,   nil,     5,   115,   nil,
    10,     8,   114,    28,    24,    29,     6,   nil,     7,     9,
    27,    28,   nil,    29,    20,    16,    25,   nil,    27,    28,
   nil,    29,   nil,   nil,    25,    23,    27,    26,   nil,    21,
    22,   nil,    25,    23,   nil,    26,   nil,    21,    22,    24,
   nil,    23,   nil,    26,   nil,    21,    22,    24,   nil,    20,
    35,   nil,   nil,   nil,    28,    24,    29,    20,    35,   nil,
   nil,    27,   nil,   nil,   nil,    20,    35,    25,   nil,   nil,
    28,   nil,    29,   nil,   nil,   nil,    23,    27,    26,   nil,
    21,    22,   nil,    25,   nil,   nil,   nil,   nil,   nil,   nil,
    24,   nil,    23,   nil,    26,     4,    21,    22,   nil,     5,
    20,    35,    10,     8,   nil,    28,    24,    29,     6,   nil,
     7,     9,    27,    28,   nil,    29,    20,    16,    25,   nil,
    27,    28,   nil,    29,   nil,   nil,    25,    23,    27,    26,
   nil,    21,    22,   nil,    25,    23,   nil,    26,   nil,    21,
    22,    24,   nil,    23,   nil,    26,   nil,    21,    22,    24,
   nil,    20,    35,   nil,   nil,   nil,    28,    24,    29,    20,
    35,   nil,   nil,    27,   nil,   nil,   nil,    20,    35,    25,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    23,   nil,
    26,     4,    21,    22,   nil,     5,   nil,   nil,    10,     8,
   nil,    28,    24,    29,     6,   nil,     7,     9,    27,   nil,
   nil,   nil,    20,    16,    25,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    23,   nil,    26,     4,    21,    22,   nil,
     5,   nil,   nil,    10,     8,   nil,    28,    24,    29,     6,
   nil,     7,     9,    27,    28,   nil,    29,    20,    16,    25,
   nil,    27,    28,   nil,    29,   nil,   nil,    25,    23,    27,
    26,   nil,    21,    22,   nil,    25,    23,   nil,    26,   nil,
    21,    22,    33,   nil,    23,   nil,    26,   nil,    21,    22,
    24,   nil,    20,    35,   nil,   nil,   nil,    28,    24,    29,
    20,    35,   nil,   nil,    27,    28,   nil,    29,    20,    35,
    25,   nil,    27,   nil,   nil,   nil,   nil,   nil,    25,    23,
   nil,    26,   nil,    21,    22,   nil,   nil,    23,   nil,    26,
   nil,    21,    22,    24,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    24,   nil,    20,    35,   nil,   nil,   nil,   nil,   nil,
   nil,    20,    35,    53,    54,    52,    55,    50,    62,    63,
   nil,    56,    57,    58,    60,    61,    59,   120,   nil,   nil,
    51,   nil,   nil,   nil,   nil,   nil,   nil,    53,    54,    52,
    55,    50,    62,    63,   nil,    56,    57,    58,    60,    61,
    59,   116,    49,   nil,    51,   nil,   nil,   nil,   nil,   nil,
    53,    54,    52,    55,    50,    62,    63,   nil,    56,    57,
    58,    60,    61,    59,    78,   nil,   nil,    51,   nil,   nil,
   nil,   nil,    53,    54,    52,    55,    50,    62,    63,   nil,
    56,    57,    58,    60,    61,    59,    85,   nil,   nil,    51,
   nil,   nil,   nil,   nil,    53,    54,    52,    55,    50,    62,
    63,   nil,    56,    57,    58,    60,    61,    59,   100,   nil,
   nil,    51,   nil,    53,    54,    52,    55,    50,    62,    63,
   nil,    56,    57,    58,    60,    61,    59,   126,   nil,   127,
    51,    53,    54,    52,    55,    50,    62,    63,   nil,    56,
    57,    58,    60,    61,    59,   nil,   101,   nil,    51,    53,
    54,    52,    55,    50,    62,    63,   nil,    56,    57,    58,
    60,    61,    59,   nil,   nil,    75,    51,    53,    54,    52,
    55,    50,    62,    63,   nil,    56,    57,    58,    60,    61,
    59,   nil,   nil,    77,    51,    53,    54,    52,    55,    50,
    62,    63,   nil,    56,    57,    58,    60,    61,    59,   nil,
   nil,   nil,    51,    53,    54,    52,    55,    50,    62,    63,
   nil,    56,    57,    58,    60,    61,    59,   nil,   nil,   nil,
    51,    53,    54,    52,    55,    50,    62,    63,   nil,    56,
    57,    58,    60,    61,    59,    53,    54,    52,    55,    50,
    62,    63,   nil,    56,    57,    58,    60,    61,    59,    53,
    54,    52,    55,    50,    62,    63,   nil,   nil,    57,    58,
    60,    61,    53,    54,    52,    55,    50,    62,    63,   nil,
   nil,    57,    58,    60,    61,    53,    54,    52,    55,    50,
    62,    63,   nil,   nil,   -60,   -60,   -60,   -60,    53,    54,
    52,    55,    50,    62,    63,   nil,   nil,   -60,   -60,   -60,
   -60,    53,    54,    52,    55,    50,    62,    63,   nil,   nil,
   -60,   -60,   -60,   -60,    53,    54,    52,    55,    50,    62,
    63,   nil,   nil,   -60,   -60,   -60,   -60 ]

racc_action_check = [
    80,     0,    80,    45,    31,     0,    31,    80,     0,     0,
     3,    30,    45,    80,     0,   132,     0,     0,     3,   132,
   132,   132,    80,     0,    80,    80,    80,    80,    37,    80,
    80,   132,    80,    80,    41,   143,    80,   143,    80,   148,
    80,    80,   143,   148,   148,   148,    80,    80,   143,    23,
    16,    89,    89,    89,   107,   148,   111,   143,    16,   143,
   143,   143,   143,    43,   143,   143,   114,   143,   143,    15,
   141,   143,   141,   143,    82,   143,   143,   141,    82,    82,
    82,   143,   143,   141,    99,    99,    99,    99,    99,    99,
    33,    33,   141,   119,   141,   141,   141,   141,   120,   141,
    24,    24,   141,   141,    14,    63,   141,    63,   141,    84,
   141,   141,    63,    90,    90,    90,   141,   141,    63,   123,
    11,     5,   126,     5,     9,   128,   130,    63,     5,    63,
     6,    63,    63,     4,     5,    98,    98,    98,    98,    98,
   133,    63,   136,     5,   137,     5,     5,     5,     5,   138,
     5,    63,    63,     5,     5,   139,   131,     5,   131,     5,
    44,     5,     5,   131,   142,     1,   144,     5,     5,   131,
    67,    67,    67,    67,    67,   146,   147,    13,   131,   nil,
   131,   131,   131,   131,   nil,   131,   131,   nil,   131,   131,
   nil,     7,   131,     7,   131,   nil,   131,   131,     7,     8,
   nil,     8,   131,   131,     7,   nil,     8,   nil,   nil,   nil,
   nil,   nil,     8,     7,   nil,     7,   nil,     7,     7,   nil,
   nil,     8,   nil,     8,   nil,     8,     8,     7,   nil,   127,
   nil,   127,   nil,   nil,   nil,     8,   127,     7,     7,   nil,
   nil,   nil,   127,   nil,   nil,     8,     8,   nil,   nil,   nil,
   nil,   127,   nil,   127,   127,   127,   127,   nil,   127,   nil,
   nil,   127,   127,   nil,    10,   127,    10,   127,   nil,   127,
   127,    10,   nil,   nil,   nil,   127,   127,    10,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    10,   nil,    10,   nil,
    10,    10,   125,   nil,   125,   nil,   nil,   nil,   nil,   125,
    10,   nil,   nil,   nil,   nil,   125,   nil,   nil,   nil,   nil,
    10,    10,   nil,   nil,   125,   nil,   125,   125,   125,   125,
   nil,   125,   125,   nil,   125,   125,   nil,    12,   125,    12,
   125,   nil,   125,   125,    12,    62,   nil,    62,   125,   125,
    12,   nil,    62,   nil,   nil,   nil,   nil,   nil,    62,    12,
   nil,    12,   nil,    12,    12,   nil,   nil,    62,   nil,    62,
   nil,    62,    62,    12,   nil,   121,   nil,   121,   nil,   nil,
   nil,    62,   121,    12,    12,   nil,   nil,   nil,   121,   nil,
   nil,    62,    62,   nil,   nil,   nil,   nil,   121,   nil,   121,
   121,   121,   121,   nil,   121,   nil,   nil,   121,   121,   nil,
   116,   121,   116,   121,   nil,   121,   121,   116,    56,   nil,
    56,   121,   121,   116,   nil,    56,   nil,   nil,   nil,   nil,
   nil,    56,   116,   nil,   116,   nil,   116,   116,   nil,   nil,
    56,   nil,    56,   nil,    56,    56,   116,   nil,    17,   nil,
    17,   nil,   nil,   nil,    56,    17,   116,   116,   nil,   nil,
   nil,    17,   nil,   nil,    56,    56,   nil,   nil,   nil,   nil,
    17,   nil,    17,    17,    17,    17,   nil,    17,    17,   nil,
    17,    17,   nil,    55,    17,    55,    17,   nil,    17,    17,
    55,   nil,   nil,   nil,    17,    17,    55,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    55,   nil,    55,   nil,    55,
    55,   105,   nil,   105,   nil,   nil,   nil,   nil,   105,    55,
   nil,   nil,   nil,   nil,   105,   nil,   nil,   nil,   nil,    55,
    55,   nil,   nil,   105,   nil,   105,   105,   105,   105,   nil,
   105,   105,   nil,   105,   105,   nil,    54,   105,    54,   105,
   nil,   105,   105,    54,    25,   nil,    25,   105,   105,    54,
   nil,    25,    26,   nil,    26,   nil,   nil,    25,    54,    26,
    54,   nil,    54,    54,   nil,    26,    25,   nil,    25,   nil,
    25,    25,    54,   nil,    26,   nil,    26,   nil,    26,    26,
    25,   nil,    54,    54,   nil,   nil,   nil,    27,    26,    27,
    25,    25,   nil,   nil,    27,    28,   nil,    28,    26,    26,
    27,   nil,    28,    29,   nil,    29,   nil,   nil,    28,    27,
    29,    27,   nil,    27,    27,   nil,    29,    28,   nil,    28,
   nil,    28,    28,    27,   nil,    29,   nil,    29,   nil,    29,
    29,    28,   nil,    27,    27,   nil,   nil,   nil,   103,    29,
   103,    28,    28,   nil,   nil,   103,   nil,   nil,   nil,    29,
    29,   103,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   103,   nil,   103,   103,   103,   103,   nil,   103,   103,   nil,
   103,   103,   103,    83,   103,    83,   103,   nil,   103,   103,
    83,    53,   nil,    53,   103,   103,    83,   nil,    53,    61,
   nil,    61,   nil,   nil,    53,    83,    61,    83,   nil,    83,
    83,   nil,    61,    53,   nil,    53,   nil,    53,    53,    83,
   nil,    61,   nil,    61,   nil,    61,    61,    53,   nil,    83,
    83,   nil,   nil,   nil,    60,    61,    60,    53,    53,   nil,
   nil,    60,   nil,   nil,   nil,    61,    61,    60,   nil,   nil,
    77,   nil,    77,   nil,   nil,   nil,    60,    77,    60,   nil,
    60,    60,   nil,    77,   nil,   nil,   nil,   nil,   nil,   nil,
    60,   nil,    77,   nil,    77,    77,    77,    77,   nil,    77,
    60,    60,    77,    77,   nil,    59,    77,    59,    77,   nil,
    77,    77,    59,    52,   nil,    52,    77,    77,    59,   nil,
    52,    76,   nil,    76,   nil,   nil,    52,    59,    76,    59,
   nil,    59,    59,   nil,    76,    52,   nil,    52,   nil,    52,
    52,    59,   nil,    76,   nil,    76,   nil,    76,    76,    52,
   nil,    59,    59,   nil,   nil,   nil,    42,    76,    42,    52,
    52,   nil,   nil,    42,   nil,   nil,   nil,    76,    76,    42,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    42,   nil,
    42,    42,    42,    42,   nil,    42,   nil,   nil,    42,    42,
   nil,    75,    42,    75,    42,   nil,    42,    42,    75,   nil,
   nil,   nil,    42,    42,    75,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    75,   nil,    75,    75,    75,    75,   nil,
    75,   nil,   nil,    75,    75,   nil,    74,    75,    74,    75,
   nil,    75,    75,    74,    58,   nil,    58,    75,    75,    74,
   nil,    58,    51,   nil,    51,   nil,   nil,    58,    74,    51,
    74,   nil,    74,    74,   nil,    51,    58,   nil,    58,   nil,
    58,    58,    74,   nil,    51,   nil,    51,   nil,    51,    51,
    58,   nil,    74,    74,   nil,   nil,   nil,    50,    51,    50,
    58,    58,   nil,   nil,    50,    57,   nil,    57,    51,    51,
    50,   nil,    57,   nil,   nil,   nil,   nil,   nil,    57,    50,
   nil,    50,   nil,    50,    50,   nil,   nil,    57,   nil,    57,
   nil,    57,    57,    50,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    57,   nil,    50,    50,   nil,   nil,   nil,   nil,   nil,
   nil,    57,    57,   104,   104,   104,   104,   104,   104,   104,
   nil,   104,   104,   104,   104,   104,   104,   112,   nil,   nil,
   104,   nil,   nil,   nil,   nil,   nil,   nil,   112,   112,   112,
   112,   112,   112,   112,   nil,   112,   112,   112,   112,   112,
   112,   104,    19,   nil,   112,   nil,   nil,   nil,   nil,   nil,
    19,    19,    19,    19,    19,    19,    19,   nil,    19,    19,
    19,    19,    19,    19,    40,   nil,   nil,    19,   nil,   nil,
   nil,   nil,    40,    40,    40,    40,    40,    40,    40,   nil,
    40,    40,    40,    40,    40,    40,    48,   nil,   nil,    40,
   nil,   nil,   nil,   nil,    48,    48,    48,    48,    48,    48,
    48,   nil,    48,    48,    48,    48,    48,    48,    70,   nil,
   nil,    48,   nil,    70,    70,    70,    70,    70,    70,    70,
   nil,    70,    70,    70,    70,    70,    70,   122,   nil,   122,
    70,   122,   122,   122,   122,   122,   122,   122,   nil,   122,
   122,   122,   122,   122,   122,   nil,    71,   nil,   122,    71,
    71,    71,    71,    71,    71,    71,   nil,    71,    71,    71,
    71,    71,    71,   nil,   nil,    36,    71,    36,    36,    36,
    36,    36,    36,    36,   nil,    36,    36,    36,    36,    36,
    36,   nil,   nil,    38,    36,    38,    38,    38,    38,    38,
    38,    38,   nil,    38,    38,    38,    38,    38,    38,   nil,
   nil,   nil,    38,    34,    34,    34,    34,    34,    34,    34,
   nil,    34,    34,    34,    34,    34,    34,   nil,   nil,   nil,
    34,    68,    68,    68,    68,    68,    68,    68,   nil,    68,
    68,    68,    68,    68,    68,    87,    87,    87,    87,    87,
    87,    87,   nil,    87,    87,    87,    87,    87,    87,    95,
    95,    95,    95,    95,    95,    95,   nil,   nil,    95,    95,
    95,    95,    92,    92,    92,    92,    92,    92,    92,   nil,
   nil,    92,    92,    92,    92,    97,    97,    97,    97,    97,
    97,    97,   nil,   nil,    97,    97,    97,    97,    93,    93,
    93,    93,    93,    93,    93,   nil,   nil,    93,    93,    93,
    93,    96,    96,    96,    96,    96,    96,    96,   nil,   nil,
    96,    96,    96,    96,    94,    94,    94,    94,    94,    94,
    94,   nil,   nil,    94,    94,    94,    94 ]

racc_action_pointer = [
   -30,   165,   nil,     7,    99,   115,    77,   185,   193,    71,
   258,   120,   321,   125,    69,    16,    47,   432,   nil,  1038,
   nil,   nil,   nil,     7,    74,   538,   546,   581,   589,   597,
     7,     2,   nil,    64,  1191,   nil,  1155,   -21,  1173,   nil,
  1060,    30,   820,    29,   155,     1,   nil,   nil,  1082,   nil,
   941,   906,   777,   675,   530,   467,   402,   949,   898,   769,
   718,   683,   329,    99,   nil,   nil,   nil,   158,  1209,   nil,
  1101,  1137,   nil,   nil,   890,   855,   785,   734,   nil,   nil,
    -6,   nil,    37,   667,    56,   nil,   nil,  1223,   nil,    37,
    99,   nil,  1250,  1276,  1302,  1237,  1289,  1263,   123,    72,
   nil,   nil,   nil,   632,   991,   495,   nil,    50,   nil,   nil,
   nil,    48,  1015,   nil,    56,   nil,   394,   nil,   nil,    41,
    45,   359,  1119,   110,   nil,   286,    74,   223,    80,   nil,
    74,   150,   -22,   131,   nil,   nil,   137,   140,   139,   112,
   nil,    64,   156,    29,   114,   nil,   166,   131,     2,   nil ]

racc_action_default = [
   -60,   -60,    -1,   -60,   -60,   -60,   -60,   -60,   -60,   -60,
   -60,   -60,   -60,   -60,   -60,   -60,   -37,   -60,   -13,   -60,
   -34,   -35,   -36,   -60,   -60,   -60,   -60,   -60,   -60,   -60,
   -60,   -60,   -30,   -32,   -33,   -37,   -60,   -60,   -60,   150,
   -60,   -60,   -60,   -17,   -60,   -23,    -4,   -15,   -60,   -14,
   -60,   -60,   -60,   -60,   -60,   -60,   -60,   -60,   -60,   -60,
   -60,   -60,   -60,   -60,   -38,   -40,   -41,   -55,   -56,   -57,
   -60,   -60,    -5,    -6,   -60,   -60,   -60,   -60,    -2,   -12,
   -60,   -18,   -60,   -60,   -60,   -16,   -39,   -42,   -43,   -44,
   -45,   -46,   -47,   -48,   -49,   -50,   -51,   -52,   -53,   -54,
   -58,   -59,   -31,   -60,   -60,   -60,    -3,   -60,   -24,   -25,
   -26,   -60,   -20,   -22,   -60,    -8,   -60,   -11,   -19,   -60,
   -60,   -60,   -60,   -60,   -21,   -60,   -60,   -60,   -60,    -7,
   -60,   -60,   -60,   -60,   -10,   -27,   -60,   -60,   -60,   -60,
   -29,   -60,   -60,   -60,   -60,    -9,   -60,   -60,   -60,   -28 ]

racc_goto_table = [
     2,    44,    34,    36,    14,    38,    32,    40,   107,    31,
   135,    43,    48,     1,   nil,   nil,   nil,    47,   nil,   nil,
    67,    68,    69,    70,    71,    17,   149,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    81,   nil,    86,    87,    88,    89,    90,
    91,    92,    93,    94,    95,    96,    97,    98,    99,   nil,
   nil,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,    34,
   113,   104,   nil,   102,   nil,    48,   nil,   nil,   112,   nil,
    47,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   103,   nil,   105,    48,   nil,
    48,   nil,   nil,    47,   nil,    47,   124,   nil,   nil,   nil,
   nil,   122,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    48,   nil,   nil,   nil,   nil,    47,    48,   nil,   nil,   nil,
   nil,    47,   nil,   nil,   nil,   nil,   nil,   nil,    48,   nil,
   nil,   125,   nil,    47,   nil,   nil,   nil,   131,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   143 ]

racc_goto_check = [
     2,     8,     3,     3,     4,     3,    11,     3,     9,     6,
    10,     7,     3,     1,   nil,   nil,   nil,     2,   nil,   nil,
     3,     3,     3,     3,     3,     5,    10,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,     4,   nil,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,   nil,
   nil,   nil,     5,   nil,   nil,   nil,   nil,   nil,   nil,     3,
     8,     3,   nil,    11,   nil,     3,   nil,   nil,     3,   nil,
     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     5,   nil,     5,     3,   nil,
     3,   nil,   nil,     2,   nil,     2,     8,   nil,   nil,   nil,
   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     3,   nil,   nil,   nil,   nil,     2,     3,   nil,   nil,   nil,
   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,
   nil,     5,   nil,     2,   nil,   nil,   nil,     5,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     5 ]

racc_goto_pointer = [
   nil,    13,     0,    -5,     0,    20,     2,    -4,   -14,   -74,
  -122,    -1 ]

racc_goto_default = [
   nil,   nil,    18,    19,   nil,   nil,   nil,   nil,   nil,   137,
   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 56, :_reduce_1,
  4, 57, :_reduce_2,
  5, 57, :_reduce_3,
  3, 57, :_reduce_4,
  3, 57, :_reduce_5,
  3, 57, :_reduce_6,
  8, 57, :_reduce_7,
  5, 57, :_reduce_8,
  13, 57, :_reduce_9,
  9, 57, :_reduce_10,
  5, 57, :_reduce_11,
  4, 57, :_reduce_12,
  1, 60, :_reduce_13,
  2, 60, :_reduce_14,
  2, 60, :_reduce_15,
  3, 60, :_reduce_16,
  2, 59, :_reduce_17,
  3, 59, :_reduce_18,
  4, 62, :_reduce_19,
  3, 63, :_reduce_20,
  5, 63, :_reduce_21,
  3, 63, :_reduce_22,
  1, 63, :_reduce_23,
  1, 64, :_reduce_24,
  1, 64, :_reduce_25,
  1, 64, :_reduce_26,
  6, 64, :_reduce_27,
  8, 65, :_reduce_28,
  2, 65, :_reduce_29,
  1, 61, :_reduce_30,
  3, 61, :_reduce_31,
  1, 66, :_reduce_32,
  1, 66, :_reduce_33,
  1, 58, :_reduce_34,
  1, 58, :_reduce_35,
  1, 58, :_reduce_36,
  1, 58, :_reduce_37,
  2, 58, :_reduce_38,
  3, 58, :_reduce_39,
  2, 58, :_reduce_40,
  2, 58, :_reduce_41,
  3, 58, :_reduce_42,
  3, 58, :_reduce_43,
  3, 58, :_reduce_44,
  3, 58, :_reduce_45,
  3, 58, :_reduce_46,
  3, 58, :_reduce_47,
  3, 58, :_reduce_48,
  3, 58, :_reduce_49,
  3, 58, :_reduce_50,
  3, 58, :_reduce_51,
  3, 58, :_reduce_52,
  3, 58, :_reduce_53,
  3, 58, :_reduce_54,
  2, 58, :_reduce_55,
  2, 58, :_reduce_56,
  2, 58, :_reduce_57,
  3, 58, :_reduce_58,
  3, 58, :_reduce_59 ]

racc_reduce_n = 60

racc_shift_n = 150

racc_token_table = {
  false => 0,
  :error => 1,
  TkComa => 2,
  TkPunto => 3,
  TkPuntoYComa => 4,
  TkDosPuntos => 5,
  TkParAbre => 6,
  TkParCierra => 7,
  TkCorcheteAbre => 8,
  TkCorcheteCierre => 9,
  TkHacer => 10,
  TkAsignacion => 11,
  TkSuma => 12,
  TkResta => 13,
  TkMult => 14,
  TkDiv => 15,
  TkMod => 16,
  TkConjuncion => 17,
  TkDisyuncion => 18,
  TkNegacion => 19,
  TkDesigualdad => 20,
  TkMenor => 21,
  TkMenorIgual => 22,
  TkMayor => 23,
  TkMayorIgual => 24,
  TkIgual => 25,
  TkSiguienteCar => 26,
  TkAnteriorCar => 27,
  TkValorAscii => 28,
  TkConcatenacion => 29,
  TkShift => 30,
  TkWith => 31,
  TkTrue => 32,
  TkFalse => 33,
  TkVar => 34,
  TkBegin => 35,
  TkEnd => 36,
  TkInt => 37,
  TkWhile => 38,
  TkIf => 39,
  TkOtherwise => 40,
  TkBool => 41,
  TkCaracter => 42,
  TkArray => 43,
  TkRead => 44,
  TkOf => 45,
  TkPrint => 46,
  TkFor => 47,
  TkStep => 48,
  TkFrom => 49,
  TkTo => 50,
  :UMINUS => 51,
  TkNum => 52,
  TkId => 53,
  TkChar => 54 }

racc_nt_base = 55

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\",\"",
  "\".\"",
  "\";\"",
  "\":\"",
  "\"(\"",
  "\")\"",
  "\"[\"",
  "\"]\"",
  "\"->\"",
  "\"<-\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"\\\\/\"",
  "\"%\"",
  "\"\\\\/\\\\\"",
  "\"\\\\\\\\/\"",
  "\"not\"",
  "\"/=\"",
  "\"<\"",
  "\"<=\"",
  "\">\"",
  "\">=\"",
  "\"=\"",
  "\"++\"",
  "\"--\"",
  "\"#\"",
  "\"::\"",
  "\"$\"",
  "\"with\"",
  "\"true\"",
  "\"false\"",
  "\"var\"",
  "\"begin\"",
  "\"end\"",
  "\"int\"",
  "\"while\"",
  "\"if\"",
  "\"otherwise\"",
  "\"bool\"",
  "\"caracter\"",
  "\"array\"",
  "\"read\"",
  "\"of\"",
  "\"print\"",
  "\"for\"",
  "\"step\"",
  "\"from\"",
  "\"to\"",
  "UMINUS",
  "\"num\"",
  "\"id\"",
  "\"char\"",
  "$start",
  "Programa",
  "Instruccion",
  "Expresion",
  "LDeclaraciones",
  "Instrucciones",
  "ElementosSalida",
  "Declaracion",
  "Argumentos",
  "Tipo",
  "Array",
  "ElementoSalida" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'Parser.y', 94)
  def _reduce_1(val, _values, result)
    result = Programa.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 97)
  def _reduce_2(val, _values, result)
      result = Asignacion.new(val[0].contenido, val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 98)
  def _reduce_3(val, _values, result)
     result = WBloque.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 99)
  def _reduce_4(val, _values, result)
      result = Bloque.new(val[1])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 100)
  def _reduce_5(val, _values, result)
      result = Read.new(val[1].contenido)  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 101)
  def _reduce_6(val, _values, result)
      result = Print.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 103)
  def _reduce_7(val, _values, result)
     result = IfOtherEnd.new(val[1], val[3], val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 104)
  def _reduce_8(val, _values, result)
     result = IfEnd.new(val[1], val[3])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 107)
  def _reduce_9(val, _values, result)
    result = Iteracion_DetStep.new(val[1].contenido,val[3], val[5], val[8], val[11])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 109)
  def _reduce_10(val, _values, result)
    result = Iteracion_Det.new(val[1].contenido,val[3], val[5], val[7])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 111)
  def _reduce_11(val, _values, result)
     result = Iteracion_Indet.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 112)
  def _reduce_12(val, _values, result)
     result = Punto.new(val[0].contenido, val[2].contenido)   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 115)
  def _reduce_13(val, _values, result)
     result = val[0]           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 116)
  def _reduce_14(val, _values, result)
     result = val[0]           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 117)
  def _reduce_15(val, _values, result)
     result = Instrucciones.new(val[0] , val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 118)
  def _reduce_16(val, _values, result)
      result = Instrucciones.new(val[0] , val[1] ) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 121)
  def _reduce_17(val, _values, result)
     result = LDeclaracionS.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 122)
  def _reduce_18(val, _values, result)
     result = LDeclaracionRec.new(val[1], val[2] )
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 125)
  def _reduce_19(val, _values, result)
     result = Declaracion.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 128)
  def _reduce_20(val, _values, result)
     result = Argumento.new(val[0].contenido , val[2], nil)
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 129)
  def _reduce_21(val, _values, result)
     result = Argumento.new(val[0].contenido , val[2] , val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 130)
  def _reduce_22(val, _values, result)
     result = ArgumentoId.new(val[0].contenido , val[2], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 131)
  def _reduce_23(val, _values, result)
     result = Argumento.new(val[0].contenido , nil, nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 134)
  def _reduce_24(val, _values, result)
     result = Int.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 135)
  def _reduce_25(val, _values, result)
     result = Bool.new() 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 136)
  def _reduce_26(val, _values, result)
     result = Caracter.new(val[0].contenido )       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 137)
  def _reduce_27(val, _values, result)
     result = DeclaracionMatriz.new(val[2].contenido, val[5])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 140)
  def _reduce_28(val, _values, result)
     result = DeclaracionMatriz.new(val[0].contenido, val[4].contenido, val[6])
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 141)
  def _reduce_29(val, _values, result)
     result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 145)
  def _reduce_30(val, _values, result)
     result = Salida.new(nil, val[0])          
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 146)
  def _reduce_31(val, _values, result)
     result = Salida.new(val[0] , val[2])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 149)
  def _reduce_32(val, _values, result)
     result = Caracter.new(val[0].contenido )       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 150)
  def _reduce_33(val, _values, result)
     result = val[0]             
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 153)
  def _reduce_34(val, _values, result)
     result = Entero.new(val[0].contenido)         
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 154)
  def _reduce_35(val, _values, result)
     result = True.new()                 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 155)
  def _reduce_36(val, _values, result)
     result = False.new()                
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 156)
  def _reduce_37(val, _values, result)
     result = Variable.new(val[0].contenido)       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 157)
  def _reduce_38(val, _values, result)
     result = ValorAscii.new(val[0])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 158)
  def _reduce_39(val, _values, result)
     result = Modulo.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 159)
  def _reduce_40(val, _values, result)
     result = SiguienteCar.new(val[0].contenido)   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 160)
  def _reduce_41(val, _values, result)
     result = AnteriorCar.new(val[0].contenido)    
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 161)
  def _reduce_42(val, _values, result)
     result = Concatenacion.new(val[0], val[2])   
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 162)
  def _reduce_43(val, _values, result)
     result = Multiplicacion.new(val[0], val[2])  
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 163)
  def _reduce_44(val, _values, result)
     result = Suma.new(val[0], val[2])            
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 164)
  def _reduce_45(val, _values, result)
     result = Resta.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 165)
  def _reduce_46(val, _values, result)
     result = Division.new(val[0], val[2])        
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 166)
  def _reduce_47(val, _values, result)
     result = Desigualdad.new(val[0], val[2])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 167)
  def _reduce_48(val, _values, result)
     result = Menor.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 168)
  def _reduce_49(val, _values, result)
     result = MenorIgual.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 169)
  def _reduce_50(val, _values, result)
     result = Igual.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 170)
  def _reduce_51(val, _values, result)
     result = Mayor.new(val[0], val[2])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 171)
  def _reduce_52(val, _values, result)
     result = MayorIgual.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 172)
  def _reduce_53(val, _values, result)
     result = And.new(val[0], val[2])     
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 173)
  def _reduce_54(val, _values, result)
     result = Or.new(val[0], val[2])      
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 174)
  def _reduce_55(val, _values, result)
     result = Not.new(val[1])             
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 175)
  def _reduce_56(val, _values, result)
     result = Shift.new(val[1])           
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 176)
  def _reduce_57(val, _values, result)
     result = MenosUnario.new(val[1])    
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 177)
  def _reduce_58(val, _values, result)
     result = val[1]                       
    result
  end
.,.,

module_eval(<<'.,.,', 'Parser.y', 178)
  def _reduce_59(val, _values, result)
     result = val[1]                       
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
